// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kugxbisasbylnnzpvrzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Z3hiaXNhc2J5bG5uenB2cnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4ODM3NDUsImV4cCI6MjA4MzQ1OTc0NX0.PgT_PlAG68SRZz_ZmvmmwiPOLw0N0zz83siU_cIPIqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);